
services:
  pghero:
    image: ankane/pghero
    ports: ["8080:8080"]
    env_file: .env
    depends_on: [postgres]
    
version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
  backend:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db

